# Generated by Django 3.1.4 on 2020-12-14 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix1', '0002_auto_20201203_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
