# Generated by Django 3.1.4 on 2020-12-16 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('netflix1', '0003_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=225)),
                ('description', models.EmailField(max_length=1000)),
                ('category_id', models.CharField(max_length=100)),
                ('image_path', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
