# Generated by Django 3.1.4 on 2020-12-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netflix1', '0004_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
